### PR TITLE
Update omniauth-oauth2 requirements

### PR DESCRIPTION
**Pull request by nikolalsvk**
CSRF vulnerabilities in < 1.1.1 versions => https://github.com/intridea/omniauth-github/commit/3c34082e3027e5d9c7c71fd5e5eb40e7ce742868

Copied requirements from `omniauth-github` => https://github.com/intridea/omniauth-github/commit/6498f617d301c12bfddb0faef41b4f8efec188c0

### CODE REVIEW

**Comment by rastasheep** [comment]
Looks awesome, i'll add you as collaborator ;)

**Comment by nikolalsvk** [comment]
Can you add this project to Semaphore so we can publish it to RubyGems easily? Right now, only you can update the gem on RubyGems :)

Or you can add to this gem on RubyGems so I can push the update.

**Comment by rastasheep** [comment]
Yeah, i've looked into rubygems.org (it's already published) and there is no collaborators there :( so semaphore is the way to go, i'll add it after lunch.

**Comment by rastasheep** [comment]
@nikolalsvk i've added it (https://semaphoreci.com/rastasheep/omniauth-cloud66), but i'm not sure what commands to put there for build/deploy, can you do that and i'll add key later or whatever we need for deployment

**Comment by nikolalsvk** [comment]
I've created a server for RubyGems, you will need to add `.gem/credentials` file to custom files and it's good to go I think

**Comment by rastasheep** [comment]
Done

**Comment by nikolalsvk** [comment]
Hmm, seems like `.gem/credentials` is not valid somehow, you can try the same steps as the server locally and then copy newly generated `.gem/credentials`

**Comment by rastasheep** [comment]
Oh sorry, my bad, wrong format :) try now

**Comment by nikolalsvk** [comment]
@rastasheep did it, thanks :)

**Pull request merged**
